### PR TITLE
Make the options arg optional in the useResettableMutation hook

### PR DESCRIPTION
**Pull request by hally9k**
Hey! Thank for this, one tweak to the optionality of the options arg if you'd like to take it.

### CODE REVIEW

**Comment by marc-ed-raffalli** [comment]
Hi @hally9k! Thanks a lot for taking the time to contribute.
I'll take care of the coverage and release over the weekend.

**Comment by marc-ed-raffalli** [comment]
@hally9k version `0.2.0` is released.
It includes your changes and a new feature `useAutoRefreshQuery`

**Comment by hally9k** [comment]
Awesome! Thanks for this BTW, really helpful little extension.

**Comment by marc-ed-raffalli** [comment]
My pleasure, happy it helps!

**Pull request merged**
